rust-lang/socket2

src/socket.rs
src/sys/unix/mod.rs
src/sys/windows.rs

Unlike the rest of the API, connect_timeout does not correspond to a
single API call. However, it's a fundamental operation, and is a pain to
set up.

Add connect_timeout

---

src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix/mod.rs
src/sys/windows.rs

We don't want to be stuck only supporting IP sockets

Add a SockAddr type

---

src/socket.rs
src/sys/unix/mod.rs
src/sys/windows.rs

I'd prefer to have constants as actual constants instead of creating it through functions but I decided to follow style as with Domain.
Due to difference in how these constants defined in winapi and libc I put implementation in sys module as otherwise I would just need to re-define all these constants in sys module...

Add protocol 'constants'

---

Cargo.toml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/windows.rs

This PR adds support for winapi 0.3 to socket2-rs. A few things to keep in mind:
- Since this library exposes winapi types in public interfaces, the version should probably be bumped to 0.3 as upgrading may be a breaking change.
- Currently this doesn't build with the winapi 0.3.2, as the `SOCKADDR_IN6_LH` struct is only in git.. This does build (and passes tests) on windows when compiled with the below additions to the winapi dep in Cargo.toml:
```
git = "https://github.com/retep998/winapi-rs.git"
branch = "0.3"
```
- The `SOCKET` type in winapi is now `usize` instead of `u64`, which doesn't match the `std::os::windows::io::RawSocket` type in Rust that's still `u64`. So this PR casts between them in a few places.

Update winapi dep to 0.3, and update code to support it

---

src/socket.rs

`i32::from(Protocol::tcp())` currently causes stack overflow. Oops!

Fix newtype conversions to i32

---

src/sockaddr.rs

The documentation incorrectly mentioned returning an SocketAddrV4
instead of a SocketAddrV6.
This fixes https://github.com/alexcrichton/socket2-rs/issues/30

Fix documentation for Socket::as_inet6()

---

src/socket.rs
src/sys/windows.rs

This fixes `Socket::nodelay()` and `Socket::set_nodelay()` for Windows by using a `c_char` instead of a `c_int`, ensuring the type size assertion in `getsockopt` does not fail.
This fixes https://github.com/alexcrichton/socket2-rs/issues/31

Fix Socket::nodelay() for Windows

---

src/sys/unix.rs

The accept4 system call is supposed to be given a pointer to an address
length, and not a length as an int. Doing so will lead to an EFAULT
error.
This fixes https://github.com/alexcrichton/socket2-rs/issues/38

Fix invalid use of accept4() system call

---

src/sockaddr.rs

This adds `as_socket_addr` with tries to convert the `SockAddr` into a `SocketAddr` if possible.
I used the same naming convention as the other `as_inet` methods.

Add as_socket_addr convenience method

---

Cargo.toml

This version compiles with modern toolchains.

cfg-if: require 0.1.6

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

This PR adds the ability to get/set SO_OOBINLINE flag for `Socket`s via the `set_out_of_band_inline`/`out_of_band_inline` methods.
Also, this PR exposes the `flags` argument of `send`/`recv` etc. methods to allow caller to specify arbitrary flags, including the `MSG_OOB` when needed.
This feature allows TCP sockets utilizing `socket2` to comply with RFC6093 regarding Urgent data etc., and allows for other uses of `send`\`recv` flags as well.

Support Out-of-Band related functionality

---

src/socket.rs
src/sys/unix.rs

As part of the preparation for rust-lang/rust#55553, add support for the Solaris-like illumos target.

Add support for illumos target

---

src/sys/windows.rs

Use Once::new on Windows

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

Moves `Domain` impl to where the type is defined  and moves Unix only `Domain` methods to unix file.

Move Domain

---

src/lib.rs
src/sys/unix.rs
src/sys/windows.rs

Although most platforms use a signed 32bit integer (i32) as C's int type it
is allowed to only be 16 bits or larger than 32 bit. Using the type as
defined by libc/winapi ensures we don't have to worry about it.

Always use C's int type

---

src/lib.rs
src/sys/unix.rs
src/sys/windows.rs
src/tests.rs

This implementation prints the named constants rather then the raw number like the derived implementation would.
/cc @stjepang

 Implement fmt::Debug for Domain, Protocol and Type

---

src/lib.rs
src/tests.rs

Useful convenience method, not sure if you think this is too high-level @alexcrichton.
I also added `#[derive(Eq, PartialEq)]`, but this is not strictly needed but useful in tests.

Add Domain::for_address

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/tests.rs

Since I didn't hear anything on #64 I went ahead and implemented it. Its a breaking change that we should log somewhere (if we choose this route). Should I start a `CHANGELOG.md`?
Closes #64
/cc @stjepang

Change constructor functions into constants

---

src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

Also change the examples to the try operator (`?`) instead of
unwrapping.

Enable some stricter warnings

---

src/lib.rs

If everyone agrees with these new goals:
* Providing a minimal API around the libc/system calls.
* Expose as much of the API as possible, possibly behind the `all` flag for API not available on all the (tier 1) OSes.

Change crate docs to reflect new crate goals

---

src/sys/unix.rs

Do not add SOCK_RDM when compiling for Haiku.

Haiku: no SOCK_RDM support in Haiku

---

src/sockaddr.rs
src/sys/unix.rs
src/sys/windows.rs
src/tests.rs

* Moves raw type definitions, such as sockaddr_storage, into the sys
module importing them in the sockaddr modules.
* Moves SockAddr::unix to src/sys/unix.rs.
* Moves the tests into the tests module.

Refactor SockAddr

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

This file is not included in this repository, and not available at the
listed URL (https://www.rust-lang.org/COPYRIGHT).
@Thomasdezeeuw

Remove references to missing COPYRIGHT file

---

src/sys/unix.rs
src/sys/windows.rs

This commit changes the byte order when converting IPv4 Addresses, as
the order was reversed.
The test program used to validate it works was sending a multicast
address to `join_multicast_v4` which was not accepted by either Windows
or Linux. Now the test program compiles and run without issues.
```rust
use socket2::{Domain, Protocol, Socket, Type};
use std::net::Ipv4Addr;
fn main() {
let socket = Socket::new(Domain::IPV4, Type::DGRAM, Some(Protocol::UDP))
.expect("could not create socket");
socket
.join_multicast_v4(&Ipv4Addr::new(224, 0, 0, 251), &Ipv4Addr::UNSPECIFIED)
.expect("could not join multicast group");
}
```
Fixes https://github.com/alexcrichton/socket2-rs/issues/87

Correc byte ordering to convert numbers to Ipv4 addresses

---

src/lib.rs

This restores backward compatibility
Fixes #93
Fixes #95

add back Domain::ipv{4,6}

---

src/lib.rs

This was added because it was a breaking change in the v0.3.x API, but
for the v0.4.x API this is no longer needed as the associated constants
would be the preferred way to create Domain.
This reverts commit 7e20f55e949054e108c5b8f114bcc8b2a0051ce7.

Revert "add back Domain::ipv{4,6} (#96)"

---

src/sys/windows.rs

IPPROTO_IPV6 is used for IPV6_ADD_MEMBERSHIP. [Source](https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ipv6-socket-options), if that's even necessary.
Minimal reproducible example:
```rust
use socket2::{Domain, Socket, Type};
use std::net::Ipv6Addr;
const IPV6_ADDR: Ipv6Addr = Ipv6Addr::new(0xff02, 0, 0, 0, 0, 0, 0, 0x00fb);
fn main() -> std::io::Result<()> {
let socket = Socket::new(Domain::IPV6, Type::DGRAM, None)?;
socket.join_multicast_v6(&IPV6_ADDR, 0)?; // returns an Err on Windows
Ok(())
}
```

Use IPPROTO_IPV6 in join_multicast_v6.

---

src/sys/unix.rs

The modern BSDs have `accept4` too, so we should use it if it is available. The existing code already contains a fallback in case the syscall doesn't exist.
DragonflyBSD has it since 4.3: https://man.dragonflybsd.org/?command=accept4&section=2 (see the HISTORY section)
FreeBSD has it since 10.0: https://www.freebsd.org/cgi/man.cgi?query=accept&&manpath=FreeBSD+10.0-RELEASE
NetBSD has it since 8.0: https://man.netbsd.org/NetBSD-8.0/accept.2
OpenBSD has it since 5.7: https://man.openbsd.org/OpenBSD-5.7/accept.2
NetBSD also has an equivalent `paccept` since 5.0, but I didn't think it worth it to add another code path for that.

Use accept4 on *BSD as well as Linux.

---

Cargo.toml
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

In this rewrite the sys module will only expose the type used by the OS
to represent a socket (e.g. SOCKET on Windows or a file descriptor on
Unix) and the required functions.
This should reduce the number of lines of code for this crate. Something
similar was done in the Mio crate which reduced the SLOC by roughly 2k.

Refactor part 1

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

If socket2 is going to be a fully configuration socket(2) wrapper, then
the user needs to determine if things like setting CLOEXEC is desirable.
The new example shows the common case of setting all those flags.
We should consider adding a `Socket::new_with_common_flags()`, which would create a socket with all advisable flags set such as in the new example.

Refactor part 2: change Socket::new to only call socket(2)

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
src/tests.rs

This PR implements vectored I/O.
It adds 4 functions, all of which take a flags argument.
* `recv_vectored`
* `recv_from_vectored`
* `send_vectored`
* `send_to_vectored`
I also considered adding separate `_with_flags` versions, and `peek_vectored` and `peek_from_vectored`, but that would have been a total of 12 new functions. To keep the API from exploding I figured this would be better: you get full flexibility, and vectored I/O is probably advanced enough that the mandatory flags argument is acceptable.
Atleast, that was my conclusion.

Implement vectored I/O.

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
src/tests.rs

The `RecvFlags` struct replaces the boolean to indicate if messages are truncated. This is intended to address #113.
Currently it only supports POSIX flags on Unix, no Linux specific flags, although that would be trivial to add.
On Windows, it only supports `is_truncated()`, because the other flags don't exist.

Return new `RecvFlags` struct with vectored I/O.

---

Cargo.toml
src/sockaddr.rs

 Don't assume memory layout of std::net::SocketAddr

---

src/sockaddr.rs
src/sys/unix.rs
src/sys/windows.rs

Porting #120 from the 0.3.x branch to master.
Fixes #121

Don't assume memory layout of std::net::SocketAddr (master)

---

Cargo.toml
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

It's easiest to review by commit, those are small self-contained changes.

Refactor part 4

---

src/socket.rs

Adds documentation about non-blocking connect and setting socket options
on Windows, meanly that it will lead to errors.

Add docs about non-blocking connect on Windows

---

src/socket.rs
src/sys/unix.rs

Additional Linux socket options
Added support for setting/getting value of:
* TCP Maximum Segment Size (TCP_MAXSEG)
* Socket Mark (SO_MARK)

Additional Linux socket options

---

src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
src/tests.rs
tests/socket.rs

Refactors the `recv` and `send` and related functions, including the `io::Read` and `io::Write` implementations.
Also changes the `Socket::new`, `Socket::pair` and `Socket::accept` functions to set close-on-exec flag on Unix, on Apple platforms `SOCK_NOSIGPIPE` and on Windows the socket is made non-inheritable. New `Socket::new_raw`, `Socket::pair_raw` and `Socket::accept_raw` functions are added which do not set the above flags. This work as done by @de-vri-es in #117.

Refactor part 5

---

src/sockaddr.rs

`sin_len` and `sin6_len` are apparently required on all BSD-like systems, from which Haiku probably inherits its network stack.
`sin_zero` has been changed from 8 bytes to 24 bytes in hrev9079 in order to stay compatible with BeOS.
This was apparently broken in #120.

Fix compilation on Haiku

---

src/sockaddr.rs

`sin_len` and `sin6_len` are apparently required on all BSD-like systems, from which Haiku probably inherits its network stack.
`sin_zero` has been changed from 8 bytes to 24 bytes in hrev9079 in order to stay compatible with BeOS.
This was apparently broken in #120.
Same as #136 but for the v0.3.x branch.

Fix compilation on Haiku on 0.3.x

---

src/sys/unix.rs

When vectored I/O was added (see pull request #107) a type definition was not
added for the "msg_iovlen" member on illumos (or Solaris) systems.  I have
added one that matches the illumos socket.h definition:
https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/sys/socket.h#L363
With this change, the tests appear to pass correctly on an illumos system:
```
$ cargo test --features all
Finished test [unoptimized + debuginfo] target(s) in 0.02s
Running target/debug/deps/socket2-3e7879ec551f2818
running 21 tests
test sockaddr::tests::conversion_v4 ... ok
test sockaddr::tests::conversion_v6 ... ok
test socket::test::nodelay ... ok
test socket::test::out_of_band_inline ... ok
test socket::test::keepalive ... ok
test socket::test::pair ... ok
test sys::test_ip ... ok
test …
```

add missing IovLen definition for illumos

---

Cargo.toml
src/lib.rs
src/socket.rs
src/sys/unix.rs

`libc` recently added more constants for redox, so some of the cfgs can be removed.

Enable some constants that are actually available on redox

---

src/lib.rs
src/sockref.rs

SockRef is a reference to a Socket that can be used to configure socket
types other than the Socket type itself, e.g. TcpStream found in the
standard library.

Add SockRef

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/options.rs
tests/socket.rs

Originally implemented by @hawkw here in
https://github.com/tokio-rs/mio/pull/1385.
Closed #126, #79.
Fixes #24.

Adopt Mio's TCP keepalive API

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Allow uninitialised buffers to be used. Also in the following functions:
* Socket::recv_out_of_band
* Socket::recv_with_flags
* Socket::peek
* Socket::recv_from
* Socket::recv_from_with_flags
* Socket::peek_from

Change Socket::recv to accept [MaybeUninit<u8>]

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

On most OSs and architectures the int type is 32 bits, however the C
spec only requires int to be 16 bits, this way we stay compatible.

Use c_int instead of i32 where appropriate

---

src/sys/unix.rs
tests/socket.rs

Extracted from #184 @Thomasdezeeuw.

Remove FFI types from the public API

---

Cargo.toml
Makefile

This updates libc to 0.2.82 which has all the constants we required on
Fuschia.
Fixes #179.

Enabled building on Fuschia

---

tests/socket.rs

Like on Windows sockets created using an IPv6 address are already IPv6
only on FreeBSD.

Fix the only_v6 test on FreeBSD

---

.github/workflows/main.yml

Part of #78 
This PR attempts to use https://github.com/vmactions/freebsd-vm to run tests in CI on a FreeBSD target. It appears to use VirtualBox virtualization on a MacOS host.
If I manage to get things working on this target then I'll try NetBSD and Solaris as well.

Add some test support for BSDs

---

.github/workflows/main.yml
src/sys/unix.rs
tests/socket.rs

Depends on https://github.com/rust-lang/libc/pull/2013 for FreeBSD.

Add more Socket options

---

src/sys/unix.rs
tests/socket.rs

"The VSOCK address family facilitates communication between virtual machines and the host they are running on.  This address family is used by guest agents and hypervisor services that need a communications channel that is in‐dependent of virtual machine network configuration." (vsock(7))
It is currently Linux-only here, but it should also be available for other systems, Windows and BSD in particular.

Add AF_VSOCK support

---

src/sys/unix.rs
tests/socket.rs

Gets or sets the value of SO_INCOMING_CPU on Linux.

Add Socket::(set_)cpu_affinity

---

CHANGELOG.md
Cargo.toml
src/sys/unix.rs

Pr #203 used mutable reference.

Fix Socket::(set_)cpu_affinity to take an immutable reference

---

src/sys/unix.rs

Musl 1.2 has switched to 64 bit `time_t`, and `libc` crate is giving deprecation warning about it on Musl targets. This PR silences that this warnings so that it doesn't break tests.
libc issue: https://github.com/rust-lang/libc/issues/1848

Fix breaking tests due to libc's deprecation of Musl time_t

---

.github/workflows/main.yml
README.md

This adds testing using rustc 1.46 in the CI.
This is now also a documented promise.

Use 1.46 as Minimum Supported Rust Version (MSRV)

---

src/sys/unix.rs

Previously, the "expected" values were implicitly encoded in
little-endian byte order with bitwise operators to match the
native (little-endian) byte order of u32s on most architectures.
This test obviously breaks when the byte order is big-endian.
Instead, convert the tested address u32 into "network endian"
bytes, and provide the expected value as an array of numbers,
as well. This has the added benefit that it's much clearer to
read, and the numbers in the array also match the ones that are
used in the Ipv4Addr constructor, and no longer have to be
constructed manually, in reverse order, with bitwise operators.
Fixes #216

Fix endianness issues in sys::unix::in_addr_convertion test

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

As far as I can tell `SO_TYPE` is defined on all platforms (though maybe CI will prove me wrong? :upside_down_face:), it's just `SO_PROTOCOL`/`SO_DOMAIN` that are specific to linux/freebsd/etc.

Enable Socket::r#type on all platforms

---

src/socket.rs
src/sockref.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

The standard library's file descriptor types have a niche of -1, allowing `Option<T>` to have the same size as `T`. By storing a `TcpStream` internally instead of a raw file descriptor, `Socket` can also take advantage of this. Currently, this incurs a slightly cost as `{from, as, into}_raw_{fd, socket}` won't be inlined, however if [this Rust PR](https://github.com/rust-lang/rust/pull/84541) is merged it will be. Storing a `TcpStream` also allows for closing to be implemented by the standard library instead of this one, which is a nice benefit.

Allow for niche optimization on Unix platforms

---

src/socket.rs
tests/socket.rs

This allows you to set IP_TRANSPARENT on sockets for linux.
To setup for a local proxy you can use the following:
ref: https://powerdns.org/tproxydoc/tproxy.md.html
```
export OUTBOUND_PORT=3100
export PROXY_PORT=3000
sudo ip rule add fwmark 1 lookup 100
sudo ip route add local 0.0.0.0/0 dev lo table 100
sudo iptables -t mangle -I POSTROUTING -p tcp --dport $OUTBOUND_PORT -j TPROXY --tproxy-mark 0x1/0x1 --on-port=$PROXY_PORT --on-ip=127.0.0.1
sudo iptables -t mangle -A OUTPUT -p tcp -m tcp --dport $OUTBOUND_PORT -j MARK --set-mark 1
```
Once done, then newly accept()'ed sockets will have the local_addr() set to the originally requested address and not the currently bound listening address.

support setting IP_TRANSPARENT on sockets

---

src/sys/unix.rs

Split off from #228. `SockAddr::vsock` can never fail, so this makes that clear to users while avoiding breaking changes.

Document `SockAddr::vsock` as infallible

---

src/socket.rs
tests/socket.rs

Sockets created by `accept` will be inheritable by default, and this library does not make them non-inheritable even when calling `Socket::accept`. This change fixes that.

Set noinherit on accepted sockets on Windows

---

src/lib.rs
src/socket.rs
src/sockref.rs
src/sys/unix.rs
src/sys/windows.rs

I tried to implement it so that as many functions are displayed on the documentation as possible regardless of the platform the docs themselves were built on. This is not possible in all cases, for example the `sys/*.rs` modules had to be left out on other platforms, but at least the union of Linux and Windows docs covers everything.
Fixes #167.

Use doc_cfg

---

src/sys/unix.rs

This fixes the build on the Haiku platform.

Haiku: define IovLen as c_int

---

.github/workflows/main.yml
Makefile

https://github.com/rust-lang/rust/pull/82216 removed the
x86_64-sun-solaris target from rustup, changing it to use
x86_64-pc-solaris instead.
Related issues:
* https://github.com/rust-lang/rust/issues/85098

Replace x86_64-sun-solaris with x86_64-pc-solaris

---

src/socket.rs
src/sockref.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

This documents some internal (un)safety around the internal `Socket::from_raw` function.
And adds an example of incorrect usage of `SockRef::from` as highlighted by #229 and #218.
Updates #229.
Updates #218.

Document some unsafety

---

Cargo.toml
src/sys/unix.rs
tests/socket.rs

I've implemented `bind_device` for Apple devices (macOS and iOS), but I've only tested this on macOS. I've tried to maintain a similar interface as on the other platforms, as far as using an interface alias goes. The issue with that is the alias needs to be a null terminated string to resolve the interface index.  These changes depend on [`IP_BOUND_IF`](https://github.com/rust-lang/libc/pull/2168) being added to `libc`, hence this is a draft PR - this provides for ample time to discuss if `bind_device` on macOS should take an interface index as a parameter rather than an alias.

Implement bind_device for Apple devices

---

src/sys/unix.rs
tests/socket.rs

TCP_USER_TIMEOUT allows the user to configure tcp connections to close if the data sits in buffers without getting sent for some user specified time. It's another angle at resolving stuck tcp connections.
I've enabled this for ~all~ most targets that libc::TCP_USER_TIMEOUT exists for (linux, android, ~l4re, emscripten,~ fuschia), but I've only tested it on linux

Support TCP_USER_TIMEOUT socket option for various unix-likes

---

src/sys/unix.rs
tests/socket.rs

Not sure whether passing abstract namespaces to `unix()` is totally supported, but there is the check below for whether to add another byte to sockaddr_len for the null terminator, which doesn't if the path starts with a null byte.

Fix size check for abstract namespaces in SockAddr::unix

---

src/lib.rs
src/sys/unix.rs

On Haiku and OpenBSD don't call `setsockopt(fd, IPPROTO_TCP,
SO_KEEPALIVE, secs)`, it is incorrect because `SO_KEEPALIVE` belongs
to `SOL_SOCKET` layer, because it accepts a boolean instead of the
number of seconds, and because there is no way to set keepalive idle
time per socket on these operating systems.
On Haiku and OpenBSD it is only possible to enable and disable
keepalives, and it is already done with `setsockopt(fd, SOL_SOCKET,
SO_KEEPALIVE, 1)` in a portable way in `Socket.set_keepalive()`
defined in `src/socket.rs`.

Fix TCP keepalive handling on Haiku and OpenBSD

---

src/sys/unix.rs

A fixup for b0732a37894fba934b2688686b4d6b22c38d5cc4
Follow-up for #251

Fix compilation error on Haiku

---

src/sockref.rs

Since we now use the niche feature on Unix it's unsound to use
SockRef::from(-1), but it can be done without any unsafe. This change
adds an assertion to ensure we hit this soundness issue.
Still need to wait on the I/O safety RFC:
https://github.com/rust-lang/rfcs/blob/master/text/3128-io-safety.md
Tracking issue: https://github.com/rust-lang/rust/issues/87074
Implementation pr: https://github.com/rust-lang/rust/pull/87329
Closes #229 (again)
Updates #218
Closes #244

Assert validity on the raw socket in SockRef::from

---

src/socket.rs
src/sys/unix.rs
tests/socket.rs

`keepalive_time()` is not available on these platforms
Fixes #255

Fix compilation on Haiku and OpenBSD with --features all

---

src/sys/unix.rs
tests/socket.rs

`freebind()`/`set_freebind()` are currently getting/setting the reuseport flag because we are passing an incorrect socket level - `SOL_SOCKET` instead of `SOL_IP`, and `SO_REUSEPORT` happens to have the same value as `IP_FREEBIND` on Linux:
```
$ git -C ~/src/linux grep -h 'define \(SO_REUSEPORT\|IP_FREEBIND\)' -- include/uapi
#define SO_REUSEPORT    15
#define IP_FREEBIND     15
```
Fix it by using `(SOL_IP, IP_FREEBIND)` and `(SOL_IPV6, IPV6_FREEBIND)` socket option (level, name) to get/set the freebind flag, for INET and INET6 sockets, respectively.
Alternatively, `(SOL_IP, IP_FREEBIND)` could be used for both IPv4 and IPv6 because Linux kernel underneath toggles a flag that is shared by v4 and v6 network stack. However, this is an implementation detail, and arguably not what would be …

Use correct socket option level and name to get/set freebind flag

---

src/lib.rs

The call to `socket.set_only_v6()` needs to be *before* the call to
`socket.bind()`.
This is for issue #259.

Example doc comment: fix usage of socket.set_only_v6()

---

src/lib.rs

Although it still spits out a bunch of errors at least the first one
will be informative about the root cause.
https://github.com/rust-lang/rust/issues/68838 tracks a version that
suppresses subsequent errors.
/cc @twitchax not a huge improvement, but still an improvement.

Add compile_error! for unsupported targets

---

src/sys/unix.rs

Hi.
This patch simply add support SO_SETFIB option to socket on a FreeBSD+ OS.
It allow to build VRF-aware applications on FreeBSD and partially solve problem with missing Bind-To-Device option on BSD.

Add support to bind socket to FIB on a FreeBSD

---

Cargo.toml
src/lib.rs
src/sys/unix.rs

Hi
This patch add support to attach filter onto socket on Linux.
See also: [Linux Socket Filtering aka Berkeley Packet Filter (BPF)](https://www.kernel.org/doc/html/v5.12/networking/filter.html)

Add support to attach filter onto socket on Linux

---

src/lib.rs
src/sockaddr.rs
src/sys/unix.rs
src/sys/windows.rs

Fixes a Clippy warning and also makes it clear how the unsafe
implementation is actually safe.

Move Send and Sync impl for MaybeUninitSlice to sys

---

src/sys/unix.rs
tests/socket.rs

Hi,
this is my first try and I ask for a review. I encounter one problem:
On my system TCP_QUICKACK is enabled by default. So the test fails. I could change the test, so that it deactivates TCP_QUICKACK, but on a different system it might be disabled by default. So that this test is flaky at the moment. 
The test could be changed that it checks if TCP_QUICKACK is enabled or not and then activate/deactivate the flag.
Closes #285

Add support for the socket options TCP_CORK, TCP_QUICKACK and TCP_THIN_LINEAR_TIMEOUTS

---

Cargo.toml

https://doc.rust-lang.org/cargo/reference/manifest.html#slash
> Previously multiple licenses could be separated with a /, but that usage is deprecated.
removes ambiguity about whether AND or OR is intended, I guess.

Modernise license format in Cargo.toml

---

CHANGELOG.md
Cargo.toml

And update to libc v0.2.114 to fix https://github.com/rust-lang/socket2/pull/284#issuecomment-1019242025.

Release v0.4.4

---

src/socket.rs
src/sys/unix.rs

Rust libc does not provide ip_mreqn for openbsd, so add it to the cfg exclusion sets where necessary.

Fix OpenBSD build

---

CHANGELOG.md

Layout related UB was fixed in 0.3.16 but it was reported in 0.4.0 which would lead people to believe they have broken dependency even if they don't.
Moving it to appropriate version avoids confusion.

Changelog: UB fix in correct version

---

Cargo.toml

Is setting equals 0.36 exactly necessary here?

Relax windows-sys dependency version

---

src/socket.rs
src/sys/unix.rs

The 0.4.5 has a regression that fails building on OpenBSD. From what I can tell `libc::IP_RECVTOS` isn't exported on OpenBSD. This looks like a similar problem in https://github.com/rust-lang/socket2/pull/291
I don't run OpenBSD but I've spotted this issue on a [youtube stream where the streamer was trying to install Helix](https://youtu.be/JGDPV4Wogyg?t=11168).
Could you cut a `0.4.6` release with this patch?

Disable RECVTOS on OpenBSD

---

src/sockaddr.rs

Fix for #310 - adds the `Clone` trait to `SockAddr` to address certain use cases.

Clone trait for SockAddr

---

.github/workflows/main.yml
Cargo.toml
README.md

Also update MSRV to 1.62. In the future we'll switch to 1.63 so we can use the I/O safety feature stabilised in 1.63: https://github.com/rust-lang/rust/pull/95118.
I've also created the v0.4.x branch for backports.

Start development of v0.5

---

.github/workflows/main.yml

Use pre-built cargo-hack in CI
The authors of cargo-hack provide an Action to use in CI and avoid having to build from source.
Currently the MSRV CI job fails because latest cargo-hack requires 1.56 to build while the test is
run with 1.46.
Simply running cargo-hack only requies 1.26 though.
This should also speedup CI runs, since we don't have to build cargo-hack each time.

Use pre-built cargo-hack in CI

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

Replaces #248.
This increases MSRV to 1.54 (released nearly a year ago).

Add links to OS documentation, attempt 3

---

.github/workflows/main.yml

It should be able to be compiled with a stable compiler since
https://github.com/rust-lang/libc/pull/2728.
Fixes #181.

Move Redox to stable checks

---

src/sockaddr.rs
src/sys/unix.rs
src/sys/windows.rs

To match the function signature, which returns a result. Also allows to
add an `init` function that never fails, if ever needed.
Updates #231.

Rename SockAddr::init to try_init

---

src/sys/unix.rs
tests/socket.rs

This code can never fail, but it was incorrect marked as fallible (by
returning an `io::Result`).
Updates #231.

Make SockAddr::vsock infallible

---

src/sockref.rs
src/sys/unix.rs
src/sys/windows.rs

I've merged the commits from #324 into this one as is was missing the implementations for `SockRef`, the most important bit.
This implements:
* The AsFd and AsSocket traits for Socket.
* From<OwnedFd> and From<OwnedSocket> for Socket.
* From<Socket> for OwnedFd and OwnedSocket.
Replacing AsRawFd with AsFd and AsRawSocket with AsSocket for SockRef.
Closed #218.

Implement the I/O-safety traits for Socket and SockRef

---

CONTRIBUTING.md
src/lib.rs
src/sockaddr.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Newer versions of Windows support AF_UNIX stream sockets. This change
adds Windows support for the `SockAddr::unix` function and the
`Domain::UNIX` constant.
Since Unix sockets are now available on all tier1 platforms, this also
removes `all` feature requirement from the `SockAddr::unix` function.

 Windows: Add support for Unix sockets

---

src/lib.rs

This brings the checks on the setters of TcpKeepalive
in line with the actual support in sys::set_tcp_keepalive().
Fixes #337 for 0.4.0x versions
(cherry picked from commit 14e99cf989f54478f017a483c6e5905e5f2e55a4)

Fix cfg target checks for TcpKeepalive

---

Cargo.toml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sockref.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

As noted in <https://github.com/rust-lang/socket2/issues/308>, switching
from winapi to windows-sys was a breaking change as we expose some of
the winapi types that are different in windows-sys.
This reverts the following commits:
* "Relax windows-sys dependency version" 81056b9c8b579c60a5760e1971032b2c6e3d6488.
* "Support Socket::(set_)recv_tos on Windows" 242e087168ab511b08e331ff004a1d8e789e2e95.
* "Replace winapi with windows-sys" aeb6c2dd3befb5e43b2d4d05f362fe6ca61653e3.
We'll make this switch in v0.5 instead.

Revert back to winapi dependency for v0.4

---

src/socket.rs
src/sys/unix.rs
tests/socket.rs

Well, it makes build and tests clean. Not sure if I'm doing it right though.
Also IP_RECVTOS support issue do prevent socket2 v0.4.6 building.

fix build on DragonFly: IP_RECVTOS and join_leave_ssm_v4() disabled

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

For OpenBSD, current master is broken.  I made some fixes to the conditional compilation configuration in the following areas:
per-socket keepalive parameters
Ipv4 source specific multicast
RECVTOS
ipv6 only
Tested on a system derived from OpenBSD 7.1, the latest published OpenBSD version.

V0.5 alpha openbsd

---

src/socket.rs
src/sys/unix.rs
tests/socket.rs

Returns the status of the to nonblocking mode of the socket.
Closes #347.
/cc @piegamesde

Add Socket::nonblocking

---

src/lib.rs
src/sys/unix.rs
tests/socket.rs

Simply add the support for MPTCP protocol by adding and exposing the MPTCP const Protocol.
MPTCP allow end user to open multiple path (TCP) to the destination server using multiple interface. For example, one can use the LTE connection of his phone as well as a Wifi connection. Or Ethernet and Wifi.
Setting this Protocol will fail if the host does not support MPTCP, thus the fallback is to open as TCP like one would normally do.
For reference: `sysctl net.mptcp.enabled=1`
I'm not sure about adding test as this imply that the host must support MPTCP, open for feedback on this :)
Signed-off-by: Martin Andre <martin.andre@tessares.net>

support IPPROTO_MPTCP

---

src/lib.rs
src/sys/unix.rs
tests/socket.rs

Adds the bare minimum needed to support SCTP sockets (IPPROTO_SCTP) as a protocol option for Linux and FreeBSD. Note that this does not include socket options specific to SCTP, as the constants and structs required have not been added to the libc crate.
Resolves #202

support IPPROTO_SCTP

---

src/sys/unix.rs
tests/socket.rs

Those values contain the original destination IPv4/IPv6 address
of the connection redirected using iptables REDIRECT or TPROXY.
Signed-off-by: Piotr Sikora <piotr@aviatrix.com>

Add support for SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST.

---

src/socket.rs

Bind an IPv6 address to an IPv6 socket, and only do it once.

Fix Socket example

---

src/sys/unix.rs
tests/socket.rs

- `tcp_congestion` uses raw syscall since diff os have diff policy on modifying len
- `set_tcp_congestion` uses raw syscall since exact str len must be passed in
Closes: #370 
Co-authored-by: Campbell He <kp.campbell.he@duskmoon314.com>

Add support for TCP_CONGESTION socketopt

---

Cargo.toml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs

Add support for QNX Neutrino to `master` branch

---

src/sys/unix.rs

New Clippy version, new lints, let's fix them.

Fix some Clippy lints

---

src/lib.rs
src/sys/unix.rs
tests/socket.rs

Authored by @onestay in #352, I just made some small tweaks and squashed the commits.

Add support for most DCCP socket options

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

Fixes #383
Does this fix your issue @fpoli?

Fix compilation with --cfg doc

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Motivation: https://github.com/tokio-rs/tokio/issues/5491

Add `Socket::peek_sender()`

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

Being deprecated, see:
* <https://github.com/rust-lang/lang-team/issues/102>
* <https://github.com/rust-lang/rust/issues/100343>

Remove usage of target_vendor = "apple"

---

.github/workflows/main.yml
README.md

I'm also deleting the https://github.com/rust-lang/socket2/tree/v0.3.x branch once this is merged.

Drop v0.3.x support

---

CHANGELOG.md
Cargo.toml

Release v0.5

---

.github/workflows/main.yml
Cargo.toml
Makefile
src/lib.rs
src/socket.rs
src/sys/unix.rs

Also adds checking the documentation to the CI for all supported targets and adds documentation generation for all the same targets on docs.rs (so we get more doc pages as well).
Fixes #397

Fix documentation generation for docs.rs

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Re: https://github.com/tokio-rs/tokio/issues/5491#issuecomment-1447923672
It was as simple as cherry-picking the commit.

0.4: backport `Socket::peek_sender()`

---

.github/workflows/main.yml
CHANGELOG.md
Cargo.toml
src/sys/windows.rs

This was cherry-pick picked from the v0.5 branch, but never compiled
properly due changed made to v0.5. Combine that with a broken CI, which
we didn't know about, and you've got a broken v0.4.8 release.
Fixes #408

Fix compilation on Windows

---

CONTRIBUTING.md
src/sockaddr.rs
src/sys/unix.rs
tests/socket.rs

Following #332, currently unix only. Should this interface also be made available on Windows?
This PR adds to `SockAddr` methods to get the path of the unix socket address on unix.
It also adds the new methods to the tests.

Match the standard library's interface for unix sockets on unix.

---

src/sockaddr.rs

Hi there,
I saw as part of #381 it was mentioned that the v0.4.x branch is not taking PRs, so apologies if this is not appropriate. When those changes were backported these `target_os` flags were not applied (I presume as the function signatures are totally different in master) which prevents compilation on 0.4 branches.
Not sure what the best way to resolve is - recommendations welcome :smile:
CC: @flba-eb @gh-tr

Add support for 'all' feature on QNX Neutrino for v0.4.x

---

.github/workflows/main.yml
Cargo.toml
Makefile
src/socket.rs

https://github.com/rust-lang/socket2/actions/runs/4582046779/jobs/8091994019
> error: component 'rust-std' for target 'x86_64-fuchsia' is unavailable for download for channel 'stable'
This is due to the following change in Rust 1.68:
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1680-2023-03-09
> Add vendor to Fuchsia's target triple

Update fuchsia target triple to fix CI failure

---

.github/workflows/main.yml
Cargo.toml
Makefile

Closes #425
- Update minimum libc version to 0.2.141.
- Add x86_64-unknown-linux-musl to CI, Makefile, and docs.rs targets.

Update libc to 0.2.141 and add x86_64-unknown-linux-musl to CI

---

src/sockaddr.rs

Add SockAddr::set_length

---

src/sys/unix.rs
tests/socket.rs

Add support for getting the socket cookie on Linux via the SO_COOKIE sockopt (#436)
There is only a getter, as the cookie is managed/created by the kernel itself.

Add support for getting SO_COOKIE socket option on linux

---

src/sys/unix.rs
tests/socket.rs

I've added IPvX versioned functions for `bind_device_by_index` and deprecated the original, as discussed in #413. 
I've added a change log entry (and thus tentatively declaring a new verison), but I'm unsure if that's the correct thing to do here.

Add v4 and v6 versions of bind_device_by_index.

---

src/lib.rs
src/socket.rs
src/sys/unix.rs

Smoke tested on esp32c3 dev board.  I've also tested a similar patch backported to v0.4.9 with much greater functionality including tokio + mio with other patches I've been working on and it's fully working.
Closes #379

Support for the ESP-IDF framework

---

src/sys/unix.rs

This was missed in #452 because I wasn't testing with feature="all" enabled for my small socket2 test.  For the full tokio integration I was using v0.4.x which didn't need this fix.
Properly closes #379.

Small fix for ESP-IDF platform support

---

src/sys/windows.rs

originally Windows SDK didn't have a `sa_family_t` typedef, and we requested `win32metadata` to add it (microsoft/win32metadata#1538) and used that from `windows-sys` as our `sa_family_t` definition on Windows platform (#414), which was an oversight. after all, Winsock2 isn't compliant to Posix and has it's own naming scheme, and `ADDRESS_FAMILY` is intended to be the equivalence of `sa_family_t`.
fixes #462

windows-sys: use ADDRESS_FAMILY for `sa_family_t`

---

src/sockaddr.rs

Fixes #468 
I don't remove `len` field because:
* `socklen_t` is larger than `u8`.
* It will introduce more platform-specific code.
* Usual socket methods (at least on macOS) don't check `ss_len`. We still need another field to pass in and out.

Assign ss_len if it exists.

---

.github/workflows/main.yml
Cargo.toml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

Hi, since the project [readme](https://github.com/rust-lang/socket2#branches) states that 0.4 is still supported, many popular crates still use 0.4 as a dependency, and to reduce the friction for developers who target Vita (currently we patch dependency to a fork), we've decided to backport #465 to 0.4 branch.
Also, if it is ok to merge this one, a side question - can we request a release of both 0.5 and this one (if/after it is merged)?
Thanks!

Added support for vita

---

CHANGELOG.md
Cargo.toml

Includes the changelog from https://github.com/rust-lang/socket2/pull/476.

Release v0.5.5

---

src/socket.rs
src/sys/unix.rs

Still a problem when trying to build/install cargo-c on Haiku, related to: https://github.com/rust-lang/socket2/issues/302
(looks some part for IP_RECVTOS has been added already, so this adds the missing parts)

Haiku fixes for IP_RECVTOS and IP_TOS

---

src/socket.rs

Added socket options for IP_MULTICAST_ALL & IPV6_MULTICAST_ALL which can be used to filter multicast packets received on the socket only from the groups that have been explicitly joined.
Useful when used in combination with SO_REUSEPORT

Socket option for IP_MULTICAST_ALL & IPV6_MULTICAST_ALL for linux

---

src/socket.rs
tests/socket.rs

Fixes typo in set_multicast_all_v4 added in #485
added tests

Fix typo in #485 (set_multicast_all_v4)

---

src/sys/unix.rs

OpenHarmony(alias ohos) is tie 3 supported target for rust. see https://github.com/rust-lang/compiler-team/issues/568.
In implementation it sits close to musl instead of bionic and napi instead jni when comparing with android.
Below is copied from ohos sdk:
```
> ag iov_max openharmony/9/native/sysroot/usr/include
openharmony/9/native/sysroot/usr/include/limits.h
50:#define IOV_MAX 1024
162:#define _XOPEN_IOV_MAX          16
openharmony/9/native/sysroot/usr/include/unistd.h
320:#define _SC_IOV_MAX 60
```

Fix compilation error with target_env=ohos

---

src/sys/unix.rs
tests/socket.rs

This is useful when reading from SocketCAN sockets. The MSG_CONFIRM flag is used to indicate a successful transmission of a CAN frame. 
Reference: https://www.kernel.org/doc/html/next/networking/can.html#raw-socket-option-can-raw-join-filters
Is there any reason the raw flags value is not exposed to the user? There might be more drivers that are using non-standard flags to communicate a certain state.

Add MSG_CONFIRM and MSG_DONTROUTE to RecvFlags

---

src/socket.rs

This is a backport of https://github.com/rust-lang/socket2/pull/369 / commit https://github.com/rust-lang/socket2/commit/ed233839be976d07f463ac3eb4dc0d6e19e333ab

Haiku: fix build as IP_RECVTOS does not exist (v0.4.x)

---

.cirrus.yml

Backport of f5367ea25de76bc45071dd3fa9bfff604b1eacc9.

Update to FreeBSD 13.2 on Cirrus CI

---

src/lib.rs
src/sys/unix.rs
src/sys/windows.rs

As stated in the title, this exposes the underlying `msg_controllen`/`Control.len` field for `MsgHdrMut`, which is necessary to figure out how many bytes, if any, were filled in the control buffer.

Add `MsgHdrMut::control_len` to get how much of control buffer was filled.

---

src/socket.rs
src/sys/unix.rs
tests/socket.rs

This PR adds the ability to get and set the value of `SO_PASSCRED` on sockets.
Theoretically, FreeBSD [does support](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234722) the equivalent behavior, but does so via differently named constants/values, so I've opted to constrain this implementation to Linux only for now.

Add `Socket::passcred`/`set_passcred` for working with `SO_PASSCRED`.

---

src/lib.rs

Ignore clippy new_without_default

---

src/socket.rs
tests/socket.rs

Also, deprecate header_included() and set_header_included() in favor of header_included_v4() and set_header_included_v4()
Close #517

Add: header_included_v6() and set_header_included_v6()

---

.cirrus.yml
.github/workflows/main.yml

And expand the amount of targets we check.
Instead of getting the target setup twice, one for the cargo check run and another for cargo doc, do it once and check both.

Merge Check, CheckTier3, Docs and DocsTier3 CI jobs

---

src/socket.rs
tests/socket.rs

See  #534
Broken since #518 - looks like BSD operating systems don't support IP_HDRINCL at the IPPROTO_IPV6 socket level like Linux and Windows; this is causing CI to fail.

Fix: header_included_v6 is broken on BSD OSes

---

Cargo.toml
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

I noticed there wasn't support for original dst in Windows, so I added it. Also add windows gnu target to allow cross compiling

feat: add support for original_dst for windows

---

src/socket.rs
src/sys/unix.rs
tests/socket.rs

Adding support for enabling IPV6_RECVHOPLIMIT on sockets for Linux OS

Ipv6 incl hop limit

---

src/sockref.rs

AsFd was moved in 1.66 which broke the old docs link.

Fix docs link for AsFd

---

Cargo.toml
src/lib.rs
src/socket.rs
src/sockref.rs
src/sys/unix.rs
src/sys/windows.rs

Make `x86_64-unknown-linux-gnu` the default target, as it's more feature rich.
Users may not realize that they can select their platform on docs.rs, so it's
better to show them more extensive documentation.
Don't pass `--cfg docsrs` to rustdoc for docs.rs builds, it's already passed by
docs.rs.
Generate documentation about supported platforms automatically from the `cfg`
attributes.

Improve documentation generation

---

src/lib.rs

The lifetimes serve as documentation.

Ignore clippy::needless-lifetimes

---

Cargo.toml
src/sys/unix.rs
tests/socket.rs

The `IP_BOUND_IF` socket option, which is wrapped by the
`Socket::bind_device_by_index_{v4,v6}` and
`Socket::device_index_{v4,v6}` is available on SunOS-like systems, such
as illumos and Solaris, as well as macOS-like systems. However, these
APIs are currently cfg-flagged to only be available on macOS-like
systems.
This commit changes the cfg attributes to also enable these APIs on
illumos and Solaris.
Fixes #560

Enable `IP_BOUND_IF` on illumos and Solaris

---

src/socket.rs
src/sys/unix.rs

This pull request introduces a platform-specific configuration to use IPV6_HDRINCL in set_header_included_v6() on Linux. 
Background: Linux has defined IPv6 specific constant IPV6_HDRINCL (36) that needs to be used when setting HDRINCL socket option instead of IP_HDRINCL (2). Without it, set_header_included_v6() function does not work as expected and a kernel provided header is added to packets sent even if `set_header_included_v6(true)` is called on a raw socket. 
* [`src/socket.rs`](diffhunk://#diff-917ff224180b881299cdcef7bc14e710509229092ea4e6599861680bc0a2a458R1677-R1679): Added conditional compilation for `IPV6_HDRINCL` on Linux and `IP_HDRINCL` on non-Linux systems to the `setsockopt` function.
* [`src/sys/unix.rs`](diffhunk://#diff-bbdb7821e30b05ce3afbaa9fbc1526c18d6670d65479baaca3 …

Use IPV6_HDRINCL in set_header_included_v6() on Linux

---

Cargo.toml
src/sys/unix.rs
tests/socket.rs

The `IP_BOUND_IF` socket option, which is wrapped by the `Socket::bind_device_by_index_{v4,v6}` and
`Socket::device_index_{v4,v6}` is available on SunOS-like systems, such as illumos and Solaris, as well as macOS-like systems. However, these APIs are currently cfg-flagged to only be available on macOS-like systems.
This commit changes the cfg attributes to also enable these APIs on illumos and Solaris.
Fixes #560
This is a backport of PR https://github.com/rust-lang/socket2/pull/561 to the v0.5.x branch.

Enable `IP_BOUND_IF` on illumos and Solaris (#561)

---

.github/workflows/main.yml
src/lib.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

This PR makes it compile on cygwin.

Add cygwin support

---

src/lib.rs
src/sys/unix.rs

A wrapper around libc::sock_filter, so we don't use any libc types in our API.

Add SockFilter

---

src/lib.rs
src/socket.rs
src/sys/windows.rs
tests/socket.rs

Bump windows sys and add support for retries on Windows

Add tcp retries to windows

---

src/sys/unix.rs
src/sys/windows.rs

As of 1.64 the canonical location to access these typedefs is `std::ffi`.

Use c_int from std::ffi instead of std::os::raw

---

src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Instead of the workaround where we use std::net::TcpStream.

Use OwnedFd/OwnedSocket in Socket

---

Cargo.toml
src/socket.rs
src/sys/windows.rs

The affected notable change is the removal of BOOLEAN type: https://github.com/microsoft/windows-rs/pull/3376

Update windows-sys to 0.60

---

CHANGELOG.md

The rename of `set_nodelay` was said to be renamed to `tcp_set_nodelay` in the CHANGELOG for 0.6.0, but was actually renamed to `set_tcp_nodelay`.

Correct rename in CHANGELOG.md

---

src/sys/unix.rs
tests/socket.rs

Useful option for latency-sensitive applications to reduce local bufferbloat by not putting (much) more than what's needed to fill the BDP into the send buffer.
I've put some some relevant links in the commit message.

Add TCP_NOTSENT_LOWAT socketopt support
