Cargo.toml
src/lib.rs
src/socket.rs
src/sys/unix/mod.rs
src/sys/windows.rs

- Depends on 0.2.37 libc release
- Corresponds to similar changes in net2

Add additional multicast operations

---

src/sys/unix/mod.rs

After upgrading to `socket2-rs` (which does clean up some code paths compared to `net2`, thanks for the recommendation) I noticed that `join_multicast_v6` and `leave_multicast_v6` were not referencing the correct protocol (causes an error on registration). This fixes that.
btw, this also includes automated rustfmt changes... let me know if you want me to revert that.
Also, do you want me to bump the version for release?

fix ipv6 proto reference for join ipv6 multicast join

---

.gitignore
src/socket.rs
src/sys/unix/mod.rs
src/sys/windows.rs

Fix keepalive

---

Cargo.toml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/redox/mod.rs
src/sys/unix/mod.rs

Might be worth releasing a libc update first before to avoid using the git version

Redox OS support

---

.travis.yml
Cargo.toml
src/socket.rs
src/sys/redox/mod.rs
src/sys/unix/mod.rs
src/sys/windows.rs

Sorry, I forgot to check the last commit of #25.

Fix compilation on redox

---

src/sockaddr.rs

`mem::uninitialized` is deprecated.

Replace mem::uninitialized with MaybeUninit

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

Also add Type::{non_blocking, cloexec} on OSes that support it.
/cc @stjepang

Move Type impl where its defined

---

src/lib.rs
src/sockaddr.rs
src/socket.rs

And moves SockAddr to sockaddr.rs

Move socket and SocketAddr

---

src/lib.rs
src/sys/unix.rs
src/sys/windows.rs
src/utils.rs

And use the newer from_{ne,be}(_bytes) functions where possible.

Remove NetInt trait

---

.github/workflows/main.yml
Cargo.toml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
src/tests.rs

This removes all features and exposes the functions previously behind a feature on all platforms that support it by default.

Remove all features

---

src/sys/unix.rs

fix: unify sigpipe settings for macos and ios

---

Cargo.toml

Release v0.3.16

---

Cargo.toml

While waiting for some 0.4 release to be ready, it would be nice to see this updated for 0.3 as well

[0.3] Update cfg-if to 1.0

---

Cargo.toml

Release v0.3.18

---

.github/workflows/main.yml
src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/options.rs

This includes this final socket options in the `SOL_SOCKET` category, which are now all grouped together in there own `impl` block.

Refactor part 7

---

src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/options.rs

This is the final massive refactor PR.

Refactor part 8: the final one

---

Cargo.toml

Since I'm now the only maintainer. @alexcrichton are you ok with this?

Add myself to the author list

---

README.md
src/lib.rs

Doc OS support

---

.github/workflows/main.yml
src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Change Socket::recv_vectored to accept uninitialised buffers

---

.github/workflows/main.yml
src/sys/unix.rs

Fix illumos target and add it to the CI

---

CONTRIBUTING.md
Cargo.toml
src/lib.rs
src/socket.rs

Add contributing guide

---

CHANGELOG.md
Cargo.toml

Add a changelog

---

README.md

And update the list of support OSs.

Add a note to the README about the support versions

---

.github/workflows/main.yml

Add a check build of Redox using Rust nightly

---

.github/workflows/main.yml

Enable CI on Fuchsia

---

CHANGELOG.md
Cargo.toml

Release v0.4.0 alpha.2

---

CHANGELOG.md
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs
tests/socket.rs

Add back `Socket::connect_timeout`

---

src/sys/unix.rs
tests/socket.rs

Fuchsia doesn't support `sendfile`.
edit: previously I asked for a point release with this because of the typo in "fuchsia", but we don't actually need it since this was for an unsupported syscall.

Fuchsia doesn't support sendfile

---

Cargo.toml
src/socket.rs
src/sys/unix.rs

Use SO_LINGER_SEC for Socket::get/set_linger on macOS

---

tests/socket.rs

Move testing of abstract namespaces to a separate test

---

CHANGELOG.md
Cargo.toml

Release v0.4.1

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Release v0.4.2

---

.github/workflows/main.yml

It keeps failing to create the VM properly.
We should switch to Cirrus CI which has nice FreeBSD support.
Closes #272

Remove the FreeBSD setup from the CI

---

src/socket.rs

Call out type conversion for Socket more

---

tests/socket.rs

Fix some of clippy warnings

---

CHANGELOG.md
Cargo.toml
src/socket.rs

Release v0.4.3

---

CHANGELOG.md
Cargo.toml

Release v0.4.5

---

README.md
src/lib.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

Use HTTPS where available and link to current version of docs page.

Update some links

---

.github/workflows/main.yml
tests/socket.rs

Add Clippy to CI

---

src/sockaddr.rs
src/sys/unix.rs
tests/socket.rs

See the individual commits.
Fixes #333.

Expand SockAddr API

---

src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
src/sys/windows.rs

Includes #334, so ignore the first four commits.

Fix a number of Clippy warnings

---

CHANGELOG.md

Release v0.4.6

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

Backport of #https://github.com/rust-lang/socket2/pull/342, https://github.com/rust-lang/socket2/pull/344 and https://github.com/rust-lang/socket2/pull/345.

Release v0.4.7

---

src/socket.rs
tests/socket.rs

CI is currently failing because of this.

Fix a clippy warning

---

tests/socket.rs

Use [Vec::spare_capacity_mut](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.spare_capacity_mut).

Use std `spare_capacity_mut`

---

src/lib.rs

Continuation of https://github.com/rust-lang/socket2/pull/294.
/cc @fulara

Remove all feature requirement from TcpKeepalive::with_interval

---

src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs
tests/socket.rs

Follow up to https://github.com/rust-lang/socket2/pull/392.

Add tvOS and watchOS

---

CHANGELOG.md
Cargo.toml

Release v0.4.8

---

CHANGELOG.md

Reflecting the changes made in https://github.com/rust-lang/socket2/pull/406.

Changelog for v0.4.8

---

src/lib.rs
src/sys/unix.rs

Add Protocol::UDPLITE

---

.github/workflows/main.yml
Cargo.toml
Makefile
src/sys/unix.rs

fixes https://github.com/rust-lang/socket2/issues/433

Add support to remaining android targets

---

src/sys/unix.rs
tests/socket.rs

FreeBSD only option: https://reviews.freebsd.org/D11003

sys/unix.rs: Added support for SO_REUSEPORT_LB

---

src/lib.rs
src/sys/unix.rs

add IPPROTO_DIVERT spport for FreeBSD and OpenBSD.

add IPPROTO_DIVERT spport

---

src/lib.rs
src/sockaddr.rs
src/socket.rs
src/sys/unix.rs

Same changes and test case as #452.

Backport ESP-IDF support from main branch

---

src/sys/windows.rs
tests/socket.rs

Don't know why this method didn't appear on Windows before:)

Add `protocol` method for Windows.

---

CHANGELOG.md
Cargo.toml

Release v0.5.6

---

.github/workflows/main.yml
README.md

Support Tier 2 `*-unknown-linux-ohos` in CI

---

CHANGELOG.md
Cargo.toml

Closes #584 
Do you like it? @Thomasdezeeuw

Release v0.5.10

---

src/sockaddr.rs
src/socket.rs
src/sockref.rs
src/sys/unix.rs

Use std::os::fd module
